version: 2.1

orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Survey app
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2024.01.1

    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - android/create-avd:
          avd-name: avd
          install: true
          system-image: system-images;android-30;default;x86_64
          additional-args: -c 2048M

      - android/start-emulator:
          avd-name: avd
          no-window: true
          post-emulator-launch-assemble-command: ./gradlew installSnapshotDebug
      - android/disable-animations
      - android/run-tests:
          test-command: ./gradlew createSnapshotDebugUnitTestCoverageReport
      - android/run-tests:
          test-command: ./gradlew createSnapshotDebugAndroidTestCoverageReport
      - store_artifacts:
          name: Store Test Results
          path: survey_app/build/outputs/androidTest-results
      - store_artifacts:
          name: Store Test Reports
          path: tables_app/build/reports

  build:
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - android/restore-gradle-cache:
          cache-prefix: v1

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - android/save-gradle-cache:
          cache-prefix: v1

      - run:
          name: Build Survey
          command: ./gradlew assembleSnapshotDebug

      - store_artifacts:
          name: Store Build Artifacts
          path: survey_app/build/outputs/apk

      - persist_to_workspace:
          root: .
          paths:
            - survey_app/build/outputs/apk

workflows:
  build-test-deploy-workflow:
    jobs:
      - build
      - test:
          requires:
            - build